name:  Depoly from ec2

on:
  workflow_run:
    workflows:
      - "Build and Push Docker Image"
    types:
      - completed
jobs:
  depoly:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name:  Deploy to EC2 via SSH
        uses:  appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script:  
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/project:latest
            docker stop app || true
            docker rm app || true
            docker run -d --restart always -p 8000:8080 ${{ secrets.DOCKERHUB_USERNAME }}/project:latest
            docker image prune -f
